import { resend } from '@/lib/resend';

const FROM_EMAIL = process.env.EMAIL_FROM || 'MedWallet <onboarding@resend.dev>';

/**
 * Send a welcome email to a new user
 * @param {string} email - Recipient email
 * @param {string} name - User's full name
 */
export async function sendWelcomeEmail(email, name) {
  try {
    console.log(`[EmailService] Sending welcome email to ${email}...`);
    const { data, error } = await resend.emails.send({
      from: FROM_EMAIL,
      to: [email],
      subject: 'Welcome to MedWallet!',
      text: `Hello ${name}, welcome to MedWallet! Your secure health wallet is ready. Access it here: ${process.env.NEXT_PUBLIC_APP_URL}/dashboard`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 12px;">
          <h2 style="color: #10b981;">Welcome to MedWallet, ${name}!</h2>
          <p>Thank you for choosing MedWallet to securely manage your health records.</p>
          <p>You can now start uploading your medical documents, tracking your records, and setting up your emergency QR code.</p>
          <div style="margin: 30px 0;">
            <a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard" style="background-color: #10b981; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">Go to Dashboard</a>
          </div>
          <p style="color: #666; font-size: 14px;">If you have any questions, feel free to reply to this email.</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="color: #999; font-size: 12px;">MedWallet — Your Health, Simplified.</p>
        </div>
      `,
    });

    if (error) {
      console.error('[EmailService] Resend error:', error);
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    console.error('[EmailService] Unexpected error:', error);
    return { success: false, error: error.message };
  }
}

/**
 * Send a password reset email
 * @param {string} email - Recipient email
 * @param {string} resetLink - The reset link generated by Supabase
 */
export async function sendPasswordResetEmail(email, resetLink) {
  try {
    console.log(`[EmailService] Sending reset email to ${email}.`);
    
    if (!resetLink) {
      throw new Error('Reset link is missing or undefined.');
    }

    const { data, error } = await resend.emails.send({
      from: FROM_EMAIL,
      to: [email],
      subject: 'Reset Your Password - MedWallet',
      text: `Reset your MedWallet password by clicking the link below:\n\n${resetLink}\n\nIf you didn't request this, you can safely ignore this email.`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 12px;">
          <h2 style="color: #333;">Password Reset Request</h2>
          <p>We received a request to reset your password for your MedWallet account.</p>
          <p>Click the button below to set a new password:</p>
          <div style="margin: 30px 0;">
            <a href="${resetLink}" style="background-color: #000; color: #fff; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">Reset Password</a>
          </div>
          <p style="color: #666; font-size: 13px;">If the button doesn't work, copy and paste this link into your browser:</p>
          <p style="color: #3b82f6; font-size: 12px; word-break: break-all;">${resetLink}</p>
          <p style="color: #666; font-size: 13px; mt-4">If you didn't request this, you can safely ignore this email.</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 25px 0;" />
          <p style="color: #999; font-size: 11px;">MedWallet — Secure Health Records Management</p>
        </div>
      `,
    });

    if (error) {
      console.error('[EmailService] Resend error:', error);
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    console.error('[EmailService] Unexpected error:', error);
    return { success: false, error: error.message };
  }
}
